from selenium import webdriver
import time

print("Test Start")
driver=webdriver.Chrome(executable_path="E:/study/Python_Program/Python_Selenium_Proj_1/Driver/chromedriver.exe")
driver.implicitly_wait(10)
driver.maximize_window()
print("Open Browser")
driver.get(url="https://opensource-demo.orangehrmlive.com/")
driver.find_element_by_id("txtUsername").send_keys("Admin")
driver.find_element_by_id("txtPassword").send_keys("admin123")
driver.find_element_by_id("btnLogin").click()
time.sleep(1)
driver.find_element_by_id("welcome").click()
time.sleep(1)
driver.find_element_by_link_text("Logout").click()
time.sleep(1)
driver.close()
driver.quit()
print("Test Complete")
